### PR TITLE
add head method and job and file management tools

### PR DESCRIPTION
**Pull request by greg-wootton**
- Updated sharedfunctions.py and callrestapi.py to support the HEAD HTTP method.
- Added tool deletejobhistory.py that will find and optionally remove any /jobExecution/job objects matching a supplied filter.
- Added a tool deleteorphanedfiles.py that will delete file objects with a non-existent parentUri
- Added a tool setjobrequestexpire.py that will update one or more jobRequests with a supplied duration, so new jobs created from the request get deleted automatically when they expire.
- Added a tool setjobrequestfolder.py to store jobRequests in a supplied folder to enable folder-based access management.

### CODE REVIEW

**Comment by gerrynelson63** [comment]
Thank you, @greg-wootton , great contributions. I will do a few tests and get them merged in.

**Comment by gerrynelson63** [comment]
Hey @greg-wootton . With python2 the formatted strings f" do not work and the tools fail where that is used. 

I am fine with the tools being Python 3 specific. But would you mind detecting the version of Python and stopping and sending a message if they are called from versions where the formatted strings do not work. I think that would be anything before 3.6. Thank you.

**Comment by greg-wootton** [comment]
@gerrynelson63 I've switched those actions to use modulo instead, does that work?

**Comment by gerrynelson63** [comment]
@greg-wootton looks good, thanks.

**Pull request merged**
