### PR TITLE
Generate a valid .json filename for Linux filesystem

### PR DESCRIPTION
**Pull request by ibodrin-rogers**
Adding get_valid_filename function to address slashes and other invalid characters in the report name for Linux filesystem.

### CODE REVIEW

**Comment by ibodrin-rogers** [comment]
The get_valid_filename function is taken from https://github.com/django/django/blob/master/django/utils/text.py.
The comment in the source says:
```
    Return the given string converted to a string that can be used for a clean
    filename. Remove leading and trailing spaces; convert other spaces to
    underscores; and remove anything that is not an alphanumeric, dash,
    underscore, or dot.
```

**Comment by gerrynelson63** [comment]
Nice improvement, thanks, I will do a little testing and merge it in.

**Comment by ibodrin-rogers** [comment]
I would actually suggest to move the function to the "sharedfunctions" modules that you already have, for consistency, and import the function in "snapshotreports" instead of declaring it in "snapshotreports".

**Comment by gerrynelson63** [comment]
Agreed, feel free to modify your branch to add the module to shared funtions.

**Comment by ibodrin-rogers** [comment]
The function is moved and commit is included in this pull request.

**Pull request merged**
